// The core blocks are the renderer every tenant runs, so they name no site and no product: what one
// site shows comes from its seed or from a plugin under src/plugins/.
import { describe, it, expect } from "vitest";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const BLOCKS = fileURLToPath(new URL("../src/blocks", import.meta.url));

/** A site, a product or a piece of demo content; `digital` is a word, and the package scope is not a product. */
const PRODUCT = /simetrix|digita(?!l)|sales\s?order|acme|aurora/i;

/** Every line of `source` that names a product, as `line-number text`. */
function productLines(source: string): string[] {
  return source.split("\n").flatMap((line, i) => (PRODUCT.test(line.replaceAll("@digitaplatform/", "")) ? [`${i + 1} ${line.trim()}`] : []));
}

function files(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? files(path) : [path];
  });
}

describe("the core blocks name no product", () => {
  const sources = files(BLOCKS);

  it("reads every file under src/blocks/, so a clean answer means it was looked at", () => {
    expect(sources.length).toBeGreaterThanOrEqual(18);
    expect(sources.some((file) => file.endsWith("HeroBrand.tsx"))).toBe(true);
    expect(sources.some((file) => file.endsWith("registry.ts"))).toBe(true);
  });

  it("finds no product literal", () => {
    const found = sources.flatMap((file) => productLines(readFileSync(file, "utf8")).map((hit) => `${relative(BLOCKS, file)}:${hit}`));
    expect(found, "a site's content belongs in its seed or in a plugin under src/plugins/").toEqual([]);
  });

  it("PLANTED DEFECT: a product in a text, a name or a literal is found", () => {
    expect(productLines('<span>generated by digita · running on digita cloud</span>')).toHaveLength(1);
    expect(productLines('<Panel title="POST /api/v1/resource/SalesOrder" />')).toHaveLength(1);
    expect(productLines('/** The approved simetrix X. */\nconst customer = "ACME GmbH";\n{ product: "Aurora Lamp" }')).toEqual([
      "1 /** The approved simetrix X. */",
      '2 const customer = "ACME GmbH";',
      '3 { product: "Aurora Lamp" }',
    ]);
    expect(productLines("options: [\"simetrix-mark\", \"none\"]\nSee www.digitaplatform.com")).toHaveLength(2);
  });

  it("PLANTED INNOCENT: the package scope and the word digital are not a product", () => {
    expect(productLines('import { Card } from "@digitaplatform/components";')).toEqual([]);
    expect(productLines("Tell us what you want to digitalize, in digital form.")).toEqual([]);
  });
});
